/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package A;

import java.awt.Component;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Asus
 */
public class Catalog extends javax.swing.JFrame {

    /**
     * Creates new form Catalog
     */
    JFrame frame;
    public Catalog() {
        initComponents();
        String [] cols = {"ID", "Name", "Quanriry", "PerPrice", "Description", "Available"};
        DefaultTableModel modal = new DefaultTableModel(null, cols);
        DataTable.setModel(modal);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtQuantity = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtPerPrice = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtDescription = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cboAvailable = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        DataTable = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        btnAdd = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Catelog Maintenance"));
        jPanel1.setLayout(new java.awt.GridLayout(6, 2, 10, 2));

        jLabel2.setText("ID");
        jPanel1.add(jLabel2);
        jPanel1.add(txtID);

        jLabel3.setText("Name");
        jPanel1.add(jLabel3);
        jPanel1.add(txtName);

        jLabel4.setText("Quantity");
        jPanel1.add(jLabel4);
        jPanel1.add(txtQuantity);

        jLabel5.setText("Per Price");
        jPanel1.add(jLabel5);
        jPanel1.add(txtPerPrice);

        jLabel1.setText("Description");
        jPanel1.add(jLabel1);
        jPanel1.add(txtDescription);

        jLabel6.setText("Available");
        jLabel6.setToolTipText("");
        jPanel1.add(jLabel6);

        cboAvailable.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Available", "Non Available" }));
        cboAvailable.setSelectedIndex(-1);
        jPanel1.add(cboAvailable);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        DataTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        DataTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DataTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(DataTable);

        jPanel2.setLayout(new java.awt.GridLayout(1, 4, 10, 10));

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        jPanel2.add(btnAdd);

        btnUpdate.setText("Update");
        btnUpdate.setEnabled(false);
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        jPanel2.add(btnUpdate);

        btnDelete.setText("Delete");
        btnDelete.setEnabled(false);
        jPanel2.add(btnDelete);

        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });
        jPanel2.add(btnReset);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 433, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 437, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        boolean isValid = validation();    
        if(isValid == false){
            return;
        }else{
            String ID = txtID.getText();
            String name = txtName.getText();
            int quantity = Integer.parseInt(txtQuantity.getText());
            double price = Double.parseDouble(txtPerPrice.getText());
            String description = txtDescription.getText();
            String available = cboAvailable.getSelectedItem().toString();
            if(DataTable.getRowCount()> -1){
                for(int i=0; i<DataTable.getRowCount(); i++){
                    String id = DataTable.getValueAt(i, 1).toString();
                    if(ID.equals(id)){
                        JOptionPane.showMessageDialog(frame, "ID must be unique!", "Error", JOptionPane.ERROR_MESSAGE );
                        return;
                    }
                }
            }
            
            DefaultTableModel model = (DefaultTableModel) DataTable.getModel();
            model.addRow(new Object[]{ID, name, quantity, price, description, available});
            JOptionPane.showMessageDialog(frame, "Added Success!", "Added Success", JOptionPane.INFORMATION_MESSAGE );
            clear();
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void DataTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DataTableMouseClicked
        int index  = DataTable.getSelectedRow();
        TableModel model = DataTable.getModel();
        String id = model.getValueAt(index, 0).toString();
        String name = model.getValueAt(index, 1).toString();
        String quantity = model.getValueAt(index, 2).toString();
        String price = model.getValueAt(index, 3).toString();
        String description = model.getValueAt(index, 4).toString();
        String available = model.getValueAt(index, 5).toString();
        
        txtID.setText(id);
        txtID.setEnabled(false);
        txtName.setText(name);
        txtQuantity.setText(quantity);
        txtPerPrice.setText(price);
        txtDescription.setText(description);
        cboAvailable.setSelectedItem(available);
        btnAdd.setEnabled(false);
        btnUpdate.setEnabled(true);
        btnDelete.setEnabled(true);
    }//GEN-LAST:event_DataTableMouseClicked

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        boolean isValid = validation();    
        if(isValid == false){
            return;
        }else{
            for(int i=0; i<DataTable.getRowCount(); i++){
                String id = DataTable.getValueAt(i, 1).toString();
                    if(txtID.getText().equals(id)){
                        String ID = txtID.getText();
                        String name = txtName.getText();
                        int quantity = Integer.parseInt(txtQuantity.getText());
                        double price = Double.parseDouble(txtPerPrice.getText());
                        String description = txtDescription.getText();
                        String available = cboAvailable.getSelectedItem().toString();
                        
                        DataTable.setValueAt(name,i,1);
                        DataTable.setValueAt(quantity,i,2);
                        DataTable.setValueAt(price,i,3);
                        DataTable.setValueAt(description,i,4);
                        DataTable.setValueAt(available,i,5);
                        JOptionPane.showMessageDialog(frame, "Updated Success!", "Updated Success", JOptionPane.INFORMATION_MESSAGE );
                        break;
                    }
            }
            clear();
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_btnResetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Catalog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Catalog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Catalog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Catalog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Catalog().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable DataTable;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cboAvailable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtDescription;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPerPrice;
    private javax.swing.JTextField txtQuantity;
    // End of variables declaration//GEN-END:variables

    private boolean validation() {
        boolean isValid = true;
        String error = "";
        if(txtID.getText().length()<=0){
            isValid = false;
            error += "ID is required!\n";
        }
        if(txtName.getText().length()<=0){
            isValid = false;
            error += "Name is required!\n";
        }
        if(txtQuantity.getText().length() <= 0){
            isValid = false;
            error += "Quantity is required!\n";
        }else{
            try{
                int quantity = Integer.parseInt(txtQuantity.getText());
                if(quantity <= 0){
                    isValid = false;
                    error += "Quantity must bigger than 0!\n";
                }
            }catch(NumberFormatException ex){
                isValid = false;
                error += "Quantity must be an integer";
            }
        }
        if(txtPerPrice.getText().length() <= 0){
            isValid = false;
            error += "Per Price is required!\n";
        }else{
            try{
                double price = Double.parseDouble(txtPerPrice.getText());
                if(price <= 0){
                    isValid = false;
                    error += "Per Price must bigger than 0!\n";
                }
            }catch(NumberFormatException ex){
                isValid = false;
                error += "Per Price must be an integer";
            }
        }
        if(txtDescription.getText().length()<=0){
            isValid = false;
            error += "Description is required!\n";
        }
        if(cboAvailable.getSelectedIndex() == -1){
            isValid= false;
            error += "Available is required!\n";
        }
        if(isValid == false){
            JOptionPane.showMessageDialog(frame, error, "Error", JOptionPane.ERROR_MESSAGE );
        }
        return isValid;
    }

    private void clear() {
        txtID.setText("") ;
        txtName.setText("");
        txtQuantity.setText("");
        txtPerPrice.setText("");
        txtDescription.setText("");
        cboAvailable.setSelectedIndex(-1);
        txtID.setEnabled(true);
        btnAdd.setEnabled(true);
        btnUpdate.setEnabled(false);
        btnDelete.setEnabled(false);
    }
}
