/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package D;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author MSI
 */
public class DeliveryOrder extends javax.swing.JFrame {

    /**
     * Creates new form DeliveryOrder
     */
    public DeliveryOrder() {
        initComponents();
        addRowToJTable();
    }
    
    public class DeliveryOrder1{
        public int paymentID;
        public String customerAdress;
        public String shippingDate;
        public String orderStatus;
        
        public DeliveryOrder1(int paymentID, String customerAdress, String shippingDate, String orderStatus){
            this.paymentID = paymentID;
            this.customerAdress = customerAdress;
            this.shippingDate = shippingDate;
            this.orderStatus = orderStatus;
        }
    }
    
    public ArrayList ListProductPurchase(){
        ArrayList<DeliveryOrder1> list = new ArrayList<DeliveryOrder1>();
        DeliveryOrder1 pp1 = new DeliveryOrder1(0001,"No.1, Taman Satu 1 Jalan Satu 31330, Kuala Lumpur.","17/10/2020","Delivering");
        DeliveryOrder1 pp2 = new DeliveryOrder1(0002,"No.1, Taman Satu 1 Jalan Satu 31330, Kuala Lumpur.","17/10/2020","Delivering");
        DeliveryOrder1 pp3 = new DeliveryOrder1(0003,"No.1, Taman Satu 1 Jalan Satu 31330, Kuala Lumpur.","17/10/2020","Delivering");
        DeliveryOrder1 pp4 = new DeliveryOrder1(0004,"No.1, Taman Satu 1 Jalan Satu 31330, Kuala Lumpur.","17/11/2020","Pending for Delivery");
        DeliveryOrder1 pp5 = new DeliveryOrder1(0005,"No.1, Taman Satu 1 Jalan Satu 31330, Kuala Lumpur.","17/11/2020","Pending for Delivery");
        list.add(pp1);
        list.add(pp2);
        list.add(pp3);
        list.add(pp4);
        list.add(pp5);
        return list;
    }
    
    public void addRowToJTable(){
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        ArrayList<DeliveryOrder1> list = ListProductPurchase();
        Object rowData[] = new Object[4];
        for(int i=0; i<list.size(); i++){
            rowData[0] = list.get(i).paymentID;
            rowData[1] = list.get(i).customerAdress;
            rowData[2] = list.get(i).shippingDate;
            rowData[3] = list.get(i).orderStatus;
            model.addRow(rowData);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Delivery Order");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Order ID", "Customer Address", "Shipping Date", "Order Status"
            }
        ));
        jScrollPane2.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setHeaderValue("Order ID");
            jTable1.getColumnModel().getColumn(1).setHeaderValue("Customer Address");
            jTable1.getColumnModel().getColumn(2).setHeaderValue("Shipping Date");
            jTable1.getColumnModel().getColumn(3).setHeaderValue("Order Status");
        }

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Update");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addGap(46, 46, 46)
                        .addComponent(jButton1))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 543, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(253, 253, 253)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(65, 65, 65))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:a
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Deliveryman().setVisible(true);
            }
        });
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeliveryOrder1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeliveryOrder1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeliveryOrder1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeliveryOrder1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DeliveryOrder().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
