/*
 * User Story: As a flower shop’s management, I want to generate monthly sales report, in order to generate revenue.
 */

package B;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.design.JasperDesign;
//import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;

/**
 *
 * @author alan0
 */
public class MonthlysSalesReport extends javax.swing.JFrame {
    MonthlySalesReportClass insertData = new MonthlySalesReportClass("Rose", 12573);
    MonthlySalesReportClass insertData2 = new MonthlySalesReportClass("Sunflower", 9860);
    /** Creates new form MonthlysSalesReport */
    public MonthlysSalesReport() {
        initComponents();
    }

    Connection con;
    PreparedStatement pst;
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        cbxMonth = new javax.swing.JComboBox<>();
        lblMonth = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        cbxYear = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMothlySalesReport = new javax.swing.JTable();
        btnPrint = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Monthly Sales Report");
        setBackground(new java.awt.Color(255, 255, 255));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lblTitle.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblTitle.setText("Monthly Sales Report");

        lblMonth.setText("Month");

        jLabel1.setText("Year");

        tblMothlySalesReport.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "items name", "Total amoung of sales"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblMothlySalesReport.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tblMothlySalesReport);
        if (tblMothlySalesReport.getColumnModel().getColumnCount() > 0) {
            tblMothlySalesReport.getColumnModel().getColumn(0).setResizable(false);
            tblMothlySalesReport.getColumnModel().getColumn(1).setResizable(false);
        }

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .add(lblTitle)
                        .add(0, 0, Short.MAX_VALUE))
                    .add(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .add(jSeparator1)))
                .addContainerGap())
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(lblMonth)
                        .add(18, 18, 18)
                        .add(cbxMonth, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 140, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(jLabel1)
                        .add(18, 18, 18)
                        .add(cbxYear, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 182, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(18, 18, 18))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                        .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 776, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(lblTitle)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jSeparator1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(lblMonth)
                    .add(cbxMonth, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel1)
                    .add(cbxYear, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 242, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        btnPrint.setMnemonic('P');
        btnPrint.setText("Print");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(btnPrint)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(btnPrint)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        int month = 0;
        int year = 2000;
        //int year = Calendar.getInstance().get(Calendar.YEAR);
        cbxMonth.removeAllItems();
        for (int i = 1; i <= 12; i++) {
            month = i;
            cbxMonth.addItem(month + "");
        }
        
        for (int i = year; i <= Calendar.getInstance().get(Calendar.YEAR); i++) {
            cbxYear.addItem(i + "");
        }
        cbxYear.setSelectedItem(Calendar.getInstance().get(Calendar.YEAR) + "");
//        try {
//            // TODO add your handling code here:
//            Class.forName("oracle.jdbc.OracleDriver");
//        } catch (ClassNotFoundException ex) {
//            Logger.getLogger(MonthlysSalesReport.class.getName()).log(Level.SEVERE, null, ex);
//            System.out.print(ex);
//        }
//        try {
//            con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","ymhomer","a800125.");
//        } catch (SQLException ex) {
//            Logger.getLogger(MonthlysSalesReport.class.getName()).log(Level.SEVERE, null, ex);
//            System.out.print(ex);
//        }
//        try {
//            JasperDesign jdesign;
//            jdesign = JRXmlLoader.load("E:\\Users\\alan0\\Documents\\GitHub\\Agile-Assignment\\src\\B\\MonthlySalesReport.jrxml");
//        } catch (JRException ex) {
//            Logger.getLogger(MonthlysSalesReport.class.getName()).log(Level.SEVERE, null, ex);
//            System.out.print(ex);
//        }
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MonthlysSalesReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MonthlysSalesReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MonthlysSalesReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MonthlysSalesReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MonthlysSalesReport().setVisible(true);
            }
        });
    }
    
    public ArrayList<MonthlySalesReportClass> monthlySalesReportList(){
        ArrayList<MonthlySalesReportClass> monthlySalesReportList = new ArrayList<>();
        //Order insertData = new OrderClass("Rose", "Lim Xiao Jie", 2, 10, 20);
        //currentCustomerName = insertData.getCustomerName();
        //TotalPrice = insertData.getTotalPrice() + insertData2.getTotalPrice();
        //orderList.add(insertData);
        //orderList.add(insertData2);
        monthlySalesReportList.add(insertData);
        monthlySalesReportList.add(insertData2);
        
        //lblTotalPrice.setText("Total : RM " + TotalPrice);
        return monthlySalesReportList;
    }
    
    public void addRowToJTable(){
        DefaultTableModel model = (DefaultTableModel)tblMothlySalesReport.getModel();
        ArrayList<MonthlySalesReportClass> monthlySalesReportList = monthlySalesReportList();
        Object rowData[] = new Object[4];
        for(int i=0; i<monthlySalesReportList.size(); i++){
            rowData[0] = monthlySalesReportList.get(i).getItemName();
            rowData[1] = monthlySalesReportList.get(i).getAmountOfSales();
            model.addRow(rowData);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPrint;
    private javax.swing.JComboBox<String> cbxMonth;
    private javax.swing.JComboBox<String> cbxYear;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblMonth;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTable tblMothlySalesReport;
    // End of variables declaration//GEN-END:variables

}
